### ISSUE TITLE
Custom code templates don't work

### ISSUE THREAD

**Issue by enumag** [ruslan-polutsygan/phpstorm-adder-remover-generator-plugin#12]
I don't really like the default code templates

```
/**
 * @param ${TYPE_HINT} ${PARAM_NAME}
 */
public function ${METHOD_NAME}(${TYPE_HINTED_PARAM})
{
#if (${IS_DOCTRINE_COLLECTION} == "doctrine")
    $this->${FIELD_NAME}->add(${PARAM_NAME});
    // uncomment if you want to update other side
    //${PARAM_NAME}->set${THIS_CLASS_NAME}($this);
#else
    $this->${FIELD_NAME}[] = ${PARAM_NAME};
#end
}
```

So I simplified it to:

```
public function ${METHOD_NAME}(${TYPE_HINTED_PARAM}): void
{
#if (${IS_DOCTRINE_COLLECTION} == "doctrine")
    $this->${FIELD_NAME}->add(${PARAM_NAME});
#else
    $this->${FIELD_NAME}[] = ${PARAM_NAME};
#end
}
```

Unfortunately when I try to use the plugin it does not work. It does not matter what change I make in the template, it simply doesn't work with customized code templates. If I revert the template it works again.

Here is the exception:

```
null
java.lang.NullPointerException
	at com.ruslanpolutsygan.adderremover.handler.ActionHandler.invoke(ActionHandler.java:73)
	at com.intellij.codeInsight.actions.CodeInsightAction.lambda$null$0(CodeInsightAction.java:73)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1030)
	at com.intellij.codeInsight.actions.CodeInsightAction.lambda$actionPerformedImpl$1(CodeInsightAction.java:76)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.a(CoreCommandProcessor.java:149)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:109)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformedImpl(CodeInsightAction.java:70)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformed(CodeInsightAction.java:43)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:216)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:151)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:231)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:968)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:958)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.a(PopupFactoryImpl.java:952)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.ui.popup.AbstractPopup.a(AbstractPopup.java:1428)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

PHPStorm info:
```
PhpStorm 2017.2.4
Build #PS-172.4155.41, built on September 15, 2017
```

**Comment by ruslan-polutsygan** [comment]
Hi @enumag 
Problem seems to be in phpdoc. For example,  following template should work:
```
/** */
public function ${METHOD_NAME}(${TYPE_HINTED_PARAM}): void
{
#if (${IS_DOCTRINE_COLLECTION} == "doctrine")
    $this->${FIELD_NAME}->add(${PARAM_NAME});
#else
    $this->${FIELD_NAME}[] = ${PARAM_NAME};
#end
}
```
Thanks for reporting. I'll fix the issue once I have time.

**Comment by enumag** [comment]
Yeah, that works. I'll use it in the meantime even though I have to remove the empty docblock manually. I just don't like docblocks with pure duplicate information - the type is already in the method code. Thanks.

**Comment by ruslan-polutsygan** [comment]
New version released. Please check
