### ISSUE TITLE
ClassCastException in PhpStorm 2016

### ISSUE THREAD

**Issue by ruslan-polutsygan** [ruslan-polutsygan/phpstorm-adder-remover-generator-plugin#4]
![exception](https://i.imgur.com/m7xSkE7.png)

**Comment by Koc** [comment]
Similar problem
```
com.intellij.util.containers.SmartHashSet cannot be cast to java.util.TreeSet
java.lang.ClassCastException: com.intellij.util.containers.SmartHashSet cannot be cast to java.util.TreeSet
	at com.ruslanpolutsygan.adderremover.handler.generators.TemplateBasedMethodGenerator.getTypeHint(TemplateBasedMethodGenerator.java:80)
	at com.ruslanpolutsygan.adderremover.handler.generators.TemplateBasedMethodGenerator.getMethodAttributes(TemplateBasedMethodGenerator.java:59)
	at com.ruslanpolutsygan.adderremover.handler.generators.TemplateBasedMethodGenerator.generate(TemplateBasedMethodGenerator.java:30)
	at com.ruslanpolutsygan.adderremover.handler.generators.ChainedGenerator.generate(ChainedGenerator.java:22)
	at com.ruslanpolutsygan.adderremover.handler.ActionHandler.invoke(ActionHandler.java:65)
	at com.intellij.codeInsight.actions.CodeInsightAction.lambda$null$0(CodeInsightAction.java:59)
	at com.intellij.codeInsight.actions.CodeInsightAction$$Lambda$1406/194298990.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:898)
	at com.intellij.codeInsight.actions.CodeInsightAction.lambda$actionPerformedImpl$1(CodeInsightAction.java:62)
	at com.intellij.codeInsight.actions.CodeInsightAction$$Lambda$1405/2079496170.run(Unknown Source)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:129)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:100)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:86)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformedImpl(CodeInsightAction.java:55)
	at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformed(CodeInsightAction.java:41)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:875)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.a(PopupFactoryImpl.java:863)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$$Lambda$946/978179874.run(Unknown Source)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
	at com.intellij.ui.popup.AbstractPopup.a(AbstractPopup.java:1390)
	at com.intellij.ui.popup.AbstractPopup$$Lambda$951/730756354.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at com.intellij.ide.IdeEventQueue.a(IdeEventQueue.java:793)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:629)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by ruslan-polutsygan** [comment]
Will try to find time to fix it on weekend

**Comment by ruslan-polutsygan** [comment]
fixed. new version published

**Comment by Koc** [comment]
thank you
